[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
